### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by nrdwr-timmmi** [gianmarcotoso/atom-hide-tabs#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: DESKTOP-32E1KQH
**Thrown From**: [atom-hide-tabs](https://github.com/gianmarcotoso/atom-hide-tabs) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of null

```
At C:\Users\Tim Friedrich\.atom\packages\atom-hide-tabs\lib\atom-hide-tabs.coffee:33

TypeError: Cannot read property 'classList' of null
    at Object.toggle (/packages/atom-hide-tabs/lib/atom-hide-tabs.coffee:33:57)
    at /packages/atom-hide-tabs/lib/atom-hide-tabs.coffee:16:89)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.0-beta0/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.21.0-beta0/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.21.0-beta0/resources/app/src/atom-environment.js:1348:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.21.0-beta0/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -8:59 settings-view:open (input.hidden-input)
     -7:57.9.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
     -6:54 intentions:highlight (input.hidden-input)
  2x -6:53.7.0 core:close (input.hidden-input)
undefined -6:45.3.0 intentions:highlight (input.hidden-input)
     -4:21.1.0 settings-view:open (input.hidden-input)
     -1:12 core:confirm (input.hidden-input)
     -0:11.3.0 atom-hide-tabs:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
atom-hide-tabs 0.3.1 
atom-ide-ui 0.3.1 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
autoclose-html 0.23.0 
busy-signal 1.4.3 
eclipse-keybindings 0.9.0 
file-icons 2.1.11 
highlight-selected 0.13.1 
intentions 1.1.5 
language-docker 1.1.8 
linter 2.2.0 
linter-docker 0.2.1 
linter-ui-default 1.6.8 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
platformio-ide-terminal 2.6.0 
project-manager 3.3.5 
```

**Comment by gianmarcotoso** [comment]
Hey,

I am not really maintaining this package anymore (or using Atom), but if you want to try and solve this I'll happily accept a PR.

**Comment by pnevyk** [comment]
PR would be very welcome, or I will try to solve it as soon as I find a free time.

**Comment by pnevyk** [comment]
@JimTim I can simply check tab bar element for null value and don't access class list if it's null. But I wonder why selecting an element with class `.tab-bar` returns null. I checked [tabs](https://github.com/atom/tabs) core package and this css class is still there. Do you have `tabs` enabled? Or can you think about a package which could somehow alter `tabs` behaviour (I tried `atom-ide-ui` from your list but still can't reproduce the error)? Or any other possible cause of this problem?
